apiVersion: v1
kind: Pod
metadata:
  labels:
    app: probes
  name: probes-http
spec:
  containers:
    - name: probes
      image: k8s.gcr.io/nginx-slim:0.8
      startupProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 1
        periodSeconds: 3
      resources:
        limits:
          cpu: 500m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
